server:
  port: 8081
spring:
  application:
    name: collector-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8090
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/webcrawlerproducercollector
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true

  liquibase:
    change-log: classpath:master.xml
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      links: 953859498b12b7926ee33080400ca65b0dc17de0c3e24828a13e6e4f06704bbf
eureka:
  instance:
    prefer-ip-address: false
    hostname: host.docker.internal
    instance-id: host.docker.internal:${spring.application.name}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
  user:
    url: localhost:8080/user
security:
  jwt:
    secret-key: 0cfa66a2831fa1659ac22cad8fd1063c502b20ff5554701f8f0224a5273d7234
    expiration-time-in-seconds: 86400
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
