server:
  port: 8080
spring:
  application:
    name: collector_service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8090
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/webcrawlerproducercollector
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  liquibase:
    change-log: classpath:master.xml
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      links: 953859498b12b7926ee33080400ca65b0dc17de0c3e24828a13e6e4f06704bbf
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
