server:
  port: 8083
spring:
  datasource:

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8093
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/webcrawlerclassifier?authSource=admin
