server:
  port: 8083
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8093
  data:
    mongodb:
      uri: mongodb+srv://weth767:Mowo7898#@@pricecatalogontology.vmsesbf.mongodb.net/
      database: pricecatalogontology