server:
  port: 8084
spring:
  application:
    name: classifier-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8094
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/webcrawlerclassifier?authSource=admin
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
  user:
    url: localhost:8080/user
security:
  jwt:
    secret-key: 0cfa66a2831fa1659ac22cad8fd1063c502b20ff5554701f8f0224a5273d7234
    expiration-time-in-seconds: 86400
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
