server:
  port: 8080
spring:
  #data:
  #mongodb:
  #authentication-database: admin
  #username: root
  #password: root
  #database: webcrawler
  #port: 27017
  #host: localhost
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8010
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/webcrawler
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  liquibase:
    change-log: classpath:master.xml