version: "3.9"
services:
  postgresproducer:
    image: postgres:14.3
    container_name: postgres_producer
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=webcrawlerproducercollector
    ports:
      - "5432:5432"
    volumes:
      - postgres_producer:/var/lib/postgresql/data
    networks:
      - webcrawler

  postgresconsumer:
    image: postgres:14.3
    container_name: postgres_consumer
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=webcrawlerconsumer
    ports:
      - "5433:5432"
    volumes:
      - postgres_consumer:/var/lib/postgresql/data
    networks:
      - webcrawler

  #postgresclassifier:
  #image: postgres:14.3
  #container_name: postgres_classifier
  #restart: always
  #environment:
  #- POSTGRES_USER=root
  #- POSTGRES_PASSWORD=root
  #- POSTGRES_DB=webcrawlerclassifier
  #ports:
  #- "5434:5432"
  #volumes:
  #- ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  #- postgres_classifier:/var/lib/postgresql/data
  #networks:
  #- webcrawler

  mongodbclassifier:
    image: mongo:7.0.6
    restart: always
    container_name: mongodb_classifier
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_DATABASE: webcrawlerclassifier
    ports:
      - "27017:27017"
    volumes:
      - ./nosql:/docker-entrypoint-initdb.d
      - mongodb_classifier:/data/db
      - mongodb_classifier:/var/log/mongodb
    networks:
      - webcrawler

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - webcrawler

  kafka:
    image: "bitnami/kafka:3.4"
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - webcrawler
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"

volumes:
  postgres_producer:
    driver: local
  postgres_consumer:
    driver: local
  #postgres_classifier:
  #driver: local
  mongodb_classifier:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  webcrawler:
    driver: bridge
