version: '3.8'
services:
  postgres:
    image: postgres:14.3
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=webcrawler
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webcrawler

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - webcrawler

  kafka:
    image: 'bitnami/kafka:3.4'
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - webcrawler
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"

volumes:
  postgres:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  webcrawler:
    driver: bridge