server:
  port: 8082
spring:
  application:
    name: producer-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    remote:
      debug:
        local-port: 8091
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      group-id: webcrawler
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      products: 6bb2322a221e8674e135be0a38698e94839900197a60e442b4a1e63e3256c40e
      links: 953859498b12b7926ee33080400ca65b0dc17de0c3e24828a13e6e4f06704bbf
eureka:
  #instance:
  #prefer-ip-address: false
  #hostname: host.docker.internal
  #instance-id: host.docker.internal:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
  user:
    url: ${GATEWAY_SERVICE_URL:http://localhost:8080/user}
security:
  jwt:
    secret-key: 0cfa66a2831fa1659ac22cad8fd1063c502b20ff5554701f8f0224a5273d7234
    expiration-time-in-seconds: 86400
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
