spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: host.docker.internal
    preferIpAddress: false
  client:
    register-with-eureka: false
    fetch-registry: false
  hystrix:
    enabled: true
