spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    preferIpAddress: false
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
  hystrix:
    enabled: true
